data:
  name: "cityscapes"
  dataset:
    root: "./cityscapes"
    mode: "fine"
    target_type: "semantic"
  loader:
    batch_size: 2

net:
  deeplab:
    pretrained: False
    resnet: "res53"
    head_in_ch: 2048
    num_classes: 20
  pointhead:
    in_c: 532 # 512 + 20
    num_classes: 20
    k: 3
    beta: 0.75

run:
  epochs: 200

apex:
  opt: "O0"